### ISSUE TITLE
General tidy up of look. Especially on Iphone

### ISSUE THREAD

**Issue by ro-savage** [in-depth/indepth-demo#34]
Generally tidy up of look and feel.

Universal bugs:
- [x] Find sort by view icons have moved.
- [x] Tidy up spacing
- [x] Page view currently doesn't go back to top on route change

iPhone bugs: 
- [x] Scrolling is really jagged
- [x] Images go over top bar
- [x] Cards don't fill to 100%

**Comment by nickmask** [comment]
Issue cloed by PR #47
