### ISSUE TITLE
Create fake inline editing of app

### ISSUE THREAD

**Issue by ro-savage** [in-depth/indepth-demo#38]
Update to allow inline editing. Probably using react-medium-editor or something basic like that.

Allow user to type in and replace any text + bold etc. Update it in local react component states (or redux) and dont save.

On app reset, it will just remove.

Add an 'admin link' somewhere, or maybe an admin page. That allows people the inline editing feature.

Make sure it can be faked nicely

**Comment by ro-savage** [comment]
I suggest just having this available on the item info page. Dont worry about any other pages.

**Comment by nickmask** [comment]
Closed by PR #68
