### ISSUE TITLE
Notifications - Demo

### ISSUE THREAD

**Issue by ro-savage** [in-depth/indepth-demo#49]
Implement a basic notification for using HTML5 Notification API.

Should click a button and then a notification appears. Place button on demo features page.
"This is a test notification. Notifications can be sent from this webapp."
Something like that

If it doesnt work on iphone make a note.

**Comment by nickmask** [comment]
Closed by PR #54 

Notes:
Should work on android but haven't been able to test due to not being https
Does not work on Safari or IOS.
